apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-workshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-workshop
  template:
    metadata:
      labels:
        app: devops-workshop
    spec:
      containers:
      - name: devops-workshop
        image: amigoscode/kubernetes:springboot-react-fullstack-v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: devops-workshop
spec:
  type: NodePort
  selector:
    app: devops-workshop
  ports:
  - port: 90
    targetPort: 9000
