services:
  workshop-repo:
    image: gunaraja/workshop-repo:hi-docker
    build: 
        context: .
    ports: 
      - 80:80

    x-aws-vpc: 
        - "vpc-0a3af2810e987b335"
    x-aws-cluster: 
        - "arn:aws:ecs:ap-south-1:933912074683:cluster/jenkins-docker-cluster"
